package com.siga.view;

import java.awt.BorderLayout;
import java.awt.Panel;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author Julio
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    public TelaPrincipal() {
        initComponents();
        PanelConteudo.setLayout(new BorderLayout());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSiga = new javax.swing.JPanel();
        textSiga = new javax.swing.JLabel();
        PanelConteudo = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        EntidadesMenu = new javax.swing.JMenu();
        MenuItemFornecedor = new javax.swing.JMenuItem();
        MenuItemCategoria = new javax.swing.JMenuItem();
        MenuItemProduto = new javax.swing.JMenuItem();
        MenuItemRequisitante = new javax.swing.JMenuItem();
        MenuItemMovimentacacao = new javax.swing.JMenuItem();
        MovimentacoesMenu = new javax.swing.JMenu();
        MenuItemEntrada = new javax.swing.JMenuItem();
        MenuItemSaida = new javax.swing.JMenuItem();
        RelatoriosMenu = new javax.swing.JMenu();
        MenuItemEstoque = new javax.swing.JMenuItem();
        MenuItemHistoricoMov = new javax.swing.JMenuItem();
        MenuItemItensCategoria = new javax.swing.JMenuItem();
        MenuItemItensFornecedor = new javax.swing.JMenuItem();
        AjudaMenu = new javax.swing.JMenu();
        MenuItemManual = new javax.swing.JMenuItem();
        MenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        PanelSiga.setBackground(new java.awt.Color(153, 153, 153));

        textSiga.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textSiga.setForeground(new java.awt.Color(51, 204, 0));
        textSiga.setText("SIGA");
        textSiga.setAlignmentX(0.5F);
        textSiga.setPreferredSize(new java.awt.Dimension(60, 32));

        javax.swing.GroupLayout PanelSigaLayout = new javax.swing.GroupLayout(PanelSiga);
        PanelSiga.setLayout(PanelSigaLayout);
        PanelSigaLayout.setHorizontalGroup(
            PanelSigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSigaLayout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(textSiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367))
        );
        PanelSigaLayout.setVerticalGroup(
            PanelSigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSigaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textSiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelConteudoLayout = new javax.swing.GroupLayout(PanelConteudo);
        PanelConteudo.setLayout(PanelConteudoLayout);
        PanelConteudoLayout.setHorizontalGroup(
            PanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelConteudoLayout.setVerticalGroup(
            PanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        LabelUsuario.setText("Usuário:");

        EntidadesMenu.setText("Entidades");

        MenuItemFornecedor.setText("Fornecedor");
        EntidadesMenu.add(MenuItemFornecedor);

        MenuItemCategoria.setText("Categoria");
        EntidadesMenu.add(MenuItemCategoria);

        MenuItemProduto.setText("Produto");
        EntidadesMenu.add(MenuItemProduto);

        MenuItemRequisitante.setText("Requisitante");
        EntidadesMenu.add(MenuItemRequisitante);

        MenuItemMovimentacacao.setText("Movimentação");
        MenuItemMovimentacacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemMovimentacacaoActionPerformed(evt);
            }
        });
        EntidadesMenu.add(MenuItemMovimentacacao);

        Menu.add(EntidadesMenu);

        MovimentacoesMenu.setText("Movimentações");

        MenuItemEntrada.setText("Entrada de Itens");
        MovimentacoesMenu.add(MenuItemEntrada);

        MenuItemSaida.setText("Saída de Itens");
        MovimentacoesMenu.add(MenuItemSaida);

        Menu.add(MovimentacoesMenu);

        RelatoriosMenu.setText("Relatórios");

        MenuItemEstoque.setText("Estoque Atual");
        RelatoriosMenu.add(MenuItemEstoque);

        MenuItemHistoricoMov.setText("Histórico de Movimentações");
        RelatoriosMenu.add(MenuItemHistoricoMov);

        MenuItemItensCategoria.setText("Itens por Categoria");
        RelatoriosMenu.add(MenuItemItensCategoria);

        MenuItemItensFornecedor.setText("Itens por Fornecedor");
        RelatoriosMenu.add(MenuItemItensFornecedor);

        Menu.add(RelatoriosMenu);

        AjudaMenu.setText("Ajuda");

        MenuItemManual.setText("Manual de Usuário");
        AjudaMenu.add(MenuItemManual);

        MenuItemSobre.setText("Sobre");
        AjudaMenu.add(MenuItemSobre);

        Menu.add(AjudaMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(PanelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelSiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(LabelUsuario))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemMovimentacacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemMovimentacacaoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemMovimentacacaoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void inciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenu EntidadesMenu;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MenuItemCategoria;
    private javax.swing.JMenuItem MenuItemEntrada;
    private javax.swing.JMenuItem MenuItemEstoque;
    private javax.swing.JMenuItem MenuItemFornecedor;
    private javax.swing.JMenuItem MenuItemHistoricoMov;
    private javax.swing.JMenuItem MenuItemItensCategoria;
    private javax.swing.JMenuItem MenuItemItensFornecedor;
    private javax.swing.JMenuItem MenuItemManual;
    private javax.swing.JMenuItem MenuItemMovimentacacao;
    private javax.swing.JMenuItem MenuItemProduto;
    private javax.swing.JMenuItem MenuItemRequisitante;
    private javax.swing.JMenuItem MenuItemSaida;
    private javax.swing.JMenuItem MenuItemSobre;
    private javax.swing.JMenu MovimentacoesMenu;
    private javax.swing.JPanel PanelConteudo;
    private javax.swing.JPanel PanelSiga;
    private javax.swing.JMenu RelatoriosMenu;
    private javax.swing.JLabel textSiga;
    // End of variables declaration//GEN-END:variables

    
    
    public void setContentPanel(JPanel panel){
        PanelConteudo.removeAll();
        PanelConteudo.add(panel, BorderLayout.CENTER);
        PanelConteudo.revalidate();
        PanelConteudo.repaint();
    }
    
    public void CategoriaListener(ActionListener listener){
        MenuItemCategoria.addActionListener(listener);
    }
    
    public void setLabelUsuario(String nome){
        LabelUsuario.setText("Usuario: " + nome);
    }
}
