package com.siga.view.entidade;
import com.siga.model.Entidade;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio
 */
public abstract class EntidadeView extends javax.swing.JPanel{

    /**
     * Creates new form CadastrarCategoria
     */
    public EntidadeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelEntidade = new javax.swing.JLabel();
        ButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaEntidade = new javax.swing.JTable();
        viewCombobox = new javax.swing.JComboBox<>();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabelEntidade.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelEntidade.setText("Entidade");

        ButtonCadastrar.setText("CADASTRAR");
        ButtonCadastrar.setAlignmentY(0.0F);

        jButtonEditar.setText("EDITAR");
        jButtonEditar.setAlignmentY(0.0F);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.setAlignmentY(0.0F);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tabelaEntidade.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tabelaEntidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEntidade.getTableHeader().setReorderingAllowed(false);
        tabelaEntidade.setRowHeight(30);
        tabelaEntidade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaEntidade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaEntidade.setShowGrid(true);
        tabelaEntidade.setUpdateSelectionOnSort(false);
        tabelaEntidade.setVerifyInputWhenFocusTarget(false);
        tabelaEntidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEntidadeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaEntidade);

        viewCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Todos", "Ativos", "Inativos"}));
        viewCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEntidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(ButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(571, 571, 571)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEntidade)
                    .addComponent(ButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void viewComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewComboboxActionPerformed

    private void tabelaEntidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEntidadeMouseClicked
        
    }//GEN-LAST:event_tabelaEntidadeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabelEntidade;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabelaEntidade;
    private javax.swing.JComboBox<String> viewCombobox;
    // End of variables declaration//GEN-END:variables
    
    //Define um contrato para ter o método "atualizarTabela" em todas as views que herdar dessa!
    public void atualizarTabela(List<? extends Entidade> entidades){};

    //Retorna a tabela
    public JTable getTabelaEntidade() {
        return tabelaEntidade;
    }

    //Define tabela
    public void setTabelaEntidade(JTable tabelaEntidade) {
        this.tabelaEntidade = tabelaEntidade;
    }
    
    //Adiciona um listener no botão de adcicionar entidade
    public void addEntidadeListenner(ActionListener listener){
        ButtonCadastrar.addActionListener(listener);
    }
    
    //Adiciona um listener no botão de editar entidade
    public void editarEntidadeListener(ActionListener listener){
        jButtonEditar.addActionListener(listener);
    }
    
    //Adiciona um listener no botão de excluir entidade
    public void excluirEntidadeListener(ActionListener listener){
        jButtonExcluir.addActionListener(listener);
    }
    
    //Insere o nome da entidade em cima da tabela
    public void setLabelEntidade(String nomeEntidade){
        jLabelEntidade.setText(nomeEntidade);
    }
    
    public String getLabelEntidade(){
        return jLabelEntidade.getText();
    }
    
    //Define a quantidade e os nomes da coluna da tabela
    public void setColunasTabela(String[] colunas) {
    DefaultTableModel tableModel = new DefaultTableModel(colunas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Todas as células não editáveis
        }
    };
    
    tabelaEntidade.setModel(tableModel);
    tabelaEntidade.getColumnModel().getColumn(0).setMaxWidth(10);
}
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    
    public String getComboView(){
        return (String) viewCombobox.getSelectedItem();
    
    }
    
    public void addFiltroComboboxListener(ActionListener listener) {
        viewCombobox.addActionListener(listener);
    }
        
    
    
    
    private final Map<Integer, Color> linhasColoridas = new HashMap<>();

    public void adicionarLinhasColoridas(int[] linhas, Color cor) {
        for (int linha : linhas) {
            linhasColoridas.put(linha, cor);
        }

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (!isSelected && linhasColoridas.containsKey(row)) {
                    c.setBackground(linhasColoridas.get(row));
                } else if (!isSelected) {
                    c.setBackground(Color.WHITE); // ou table.getBackground()
                } else {
                    c.setBackground(table.getSelectionBackground());
                }

                return c;
            }
        };

        for (int i = 0; i < tabelaEntidade.getColumnCount(); i++) {
            tabelaEntidade.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        tabelaEntidade.repaint();
    }
    
    public void setButExcluirText(String str){
        jButtonExcluir.setText(str);
    }
    
    public void tabelaEntidadeMouseListener(MouseListener listener) {
    tabelaEntidade.addMouseListener(listener);
}

};

    
    
    
    
    
    
   


    
    

    

    

