package com.siga.view.entidade;
import com.siga.model.Categoria;
import com.siga.model.Entidade;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio
 */
public abstract class PanelPrincipal extends javax.swing.JPanel{

    /**
     * Creates new form CadastrarCategoria
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelEntidade = new javax.swing.JLabel();
        ButtonCadastrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaEntidade = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabelEntidade.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelEntidade.setText("Entidade");

        ButtonCadastrar.setText("CADASTRAR");

        tabelaEntidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "DESCRIÇÃO", "AÇÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEntidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaEntidade.setEditingColumn(0);
        tabelaEntidade.setEditingRow(0);
        tabelaEntidade.setFocusable(false);
        tabelaEntidade.setMaximumSize(new java.awt.Dimension(727, 0));
        tabelaEntidade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaEntidade.setShowGrid(true);
        tabelaEntidade.getTableHeader().setResizingAllowed(false);
        tabelaEntidade.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaEntidade);
        if (tabelaEntidade.getColumnModel().getColumnCount() > 0) {
            tabelaEntidade.getColumnModel().getColumn(0).setResizable(false);
            tabelaEntidade.getColumnModel().getColumn(1).setResizable(false);
            tabelaEntidade.getColumnModel().getColumn(2).setResizable(false);
            tabelaEntidade.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelEntidade)
                                .addGap(503, 503, 503)
                                .addComponent(ButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEntidade)
                    .addComponent(ButtonCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabelEntidade;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabelaEntidade;
    // End of variables declaration//GEN-END:variables
    
    //Define um contrato para ter o método "atualizarTabela" em todas as views que herdar dessa!
    public void atualizarTabela(List<? extends Entidade> entidades){};

    //Retorna a tabela
    public JTable getTabelaEntidade() {
        return tabelaEntidade;
    }

    //Define tabela
    public void setTabelaEntidade(JTable tabelaEntidade) {
        this.tabelaEntidade = tabelaEntidade;
    }
    
    //Adiciona um listener no botão de adcicionar entidade
    public void addEntidadeListenner(ActionListener listener){
        ButtonCadastrar.addActionListener(listener);
    }
    
    //Adiciona um listener no botão de editar entidade
    public void editarEntidadeListener(ActionListener listener){
        jButtonEditar.addActionListener(listener);
    }
    
    //Adiciona um listener no botão de excluir entidade
    public void excluirEntidadeListener(ActionListener listener){
        jButtonExcluir.addActionListener(listener);
    }
    
    //Insere o nome da entidade em cima da tabela
    public void setLabelEntidade(String nomeEntidade){
        jLabelEntidade.setText(nomeEntidade);
    }
    
    public String getLabelEntidade(){
        return jLabelEntidade.getText();
    }
    
    //Define a quantidade e os nomes da coluna da tabela
    public void setColunasTabela(String[] colunas){
        DefaultTableModel tableModel = new DefaultTableModel(colunas, 0);
        tabelaEntidade.setModel(tableModel);
    }
    
}
